# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  # Lascia le righe della Corne se vuoi continuare a buildare anche quelle,
  # altrimenti puoi rimuoverle.
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right

  # AGGIUNGI QUESTA SEZIONE PER LA TUA TASTIERA CYGNUS
  - board: nice_nano_v2 # La board del tuo controller nRF52840
    shield: cygnus      # Il nome della cartella del tuo nuovo shield (esattamente "cygnus")
    # Opzionale: puoi dare un nome più descrittivo all'artifact
    artifact-name: cygnus_handwired
    # Opzionale: Se la tua configurazione (corne.conf/corne.keymap) è in una sottocartella specifica
    # all'interno di 'config/', puoi specificarla qui.
    # Se i tuoi file sono in 'config/corne/', non è strettamente necessario,
    # ma se li sposti in 'config/cygnus_config/', allora lo sarà.
    # Esempio se hai una cartella 'config/cygnus_config/':
    # zmk-config: config/cygnus_config