# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  # QUESTA È LA RIGA FONDAMENTALE CHE DEVE ESSERE PRESENTE E CORRETTA
  - board: nice_nano_v2 # <<< Assicurati che questo sia il nome esatto della tua board
    shield: cygnus      # <<< Questo DEVE essere il nome esatto della cartella del tuo shield
    artifact-name: cygnus_handwired # Opzionale, ma utile
    # Se hai spostato corne.conf/keymap in config/cygnus_config/
    # zmk-config: config/cygnus_config